INSERT INTO parametros_soap (codigo, campo, descripcion, tabla, donde, unidad_medida) 
VALUES ('GUAVIO', 'OPBAGU_TOT_DESC_BAT', 'CAUDAL DESVIACION BATATAS', 'EMG_OPO_BAT_GU', 'OPBAGU_FECHA', 'M3/S');

ALTER TABLE emg_opo_bat_gu ADD (
  OPBAGU_H1_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H2_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H3_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H4_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H5_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H6_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H7_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H8_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H9_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H10_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H11_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H12_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H13_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H14_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H15_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H16_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H17_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H18_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H19_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H20_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H21_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H22_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H23_TOT_DESC_BAT NUMBER(7,2),
  OPBAGU_H24_TOT_DESC_BAT NUMBER(7,2)
);

DROP TABLE servicios_ingen_log;
DROP SEQUENCE seq_servicios_ingen_log;

CREATE TABLE servicios_ingen_log (
  id NUMBER(5) PRIMARY KEY,
  estado_ejecucion VARCHAR2(200) NOT NULL,
  fecha_ejecucion DATE
);

CREATE SEQUENCE seq_servicios_ingen_log  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE ;

CREATE OR REPLACE TRIGGER trg_servicios_ingen_log 
BEFORE INSERT ON servicios_ingen_log  
FOR EACH ROW
BEGIN
  :NEW.id := seq_servicios_ingen_log.NEXTVAL;
  :NEW.fecha_ejecucion := SYSDATE;
END;