INSERT INTO perfil (perfil_id, perfil) VALUES (NULL, 'Asesor'), (NULL, 'Validador de pagos');

ALTER TABLE remitente CHANGE remitente_usuario_id remitente_usuario_id INT(11) NULL;
ALTER TABLE remitente ADD remitente_password VARCHAR(200) NULL AFTER remitente_telefono;
ALTER TABLE remitente ADD remitente_estado_id INT NOT NULL DEFAULT '1' AFTER remitente_usuario_id;
ALTER TABLE remitente ADD CONSTRAINT fk_remitente_estado_id FOREIGN KEY (remitente_estado_id) REFERENCES usuario_estado(usuario_estado_id);


ALTER TABLE receptor ADD receptor_remitente_id INT NULL AFTER receptor_usuario_id;
ALTER TABLE receptor ADD CONSTRAINT fk_receptor_remitente_id FOREIGN KEY (receptor_remitente_id) REFERENCES remitente(remitente_id);
ALTER TABLE receptor CHANGE receptor_usuario_id receptor_usuario_id INT(11) NULL;
ALTER TABLE receptor DROP INDEX uk_receptor_documento;
ALTER TABLE receptor ADD CONSTRAINT uk_documento_remitente UNIQUE (receptor_documento,receptor_remitente_id, receptor_numero_cuenta);
ALTER TABLE receptor ADD CONSTRAINT fk_receptor_tipo_documento FOREIGN KEY (receptor_tipo_documento) REFERENCES tipo_documento(tipo_documento_sigla);

ALTER TABLE giro_estado CHANGE giro_estado giro_estado VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
INSERT INTO giro_estado (giro_estado_id, giro_estado) VALUES (NULL, 'Pendiente de pago'), (NULL, 'Pendiente de validación'), (NULL, 'Pago errado');
ALTER TABLE giro ADD giro_imagen VARCHAR(4) NULL AFTER giro_url;

CREATE TABLE IF NOT EXISTS tipo_documento(
  tipo_documento_id INT NOT NULL AUTO_INCREMENT,
  tipo_documento_sigla CHAR(1) NOT NULL,
  tipo_documento CHAR(20) NOT NULL,
  PRIMARY KEY (tipo_documento_id),
  UNIQUE (tipo_documento_sigla)
);
INSERT INTO tipo_documento (tipo_documento_sigla, tipo_documento) 
VALUES ("V", "Cédula venezolana"),
("E", "Extranjería"),
("P", "Pasaporte"),
("J", "RIF");
UPDATE receptor SET receptor_tipo_documento='V' WHERE receptor_tipo_documento NOT IN ('V','E','P','J');

ALTER TABLE banco ADD banco_interbancario TINYINT NOT NULL DEFAULT '1' AFTER banco_codigo;
update banco set banco_interbancario = 0 where banco NOT like 'Interbancario%';

ALTER TABLE banco ADD banco_tasa FLOAT(5,4) DEFAULT '0' AFTER banco;

ALTER TABLE remitente ADD remitente_correo VARCHAR(100) NULL AFTER remitente_nombre;
ALTER TABLE receptor CHANGE receptor_documento receptor_documento VARCHAR(15) NOT NULL;

ALTER TABLE remitente ADD remitente_regalo VARCHAR(20) NULL AFTER remitente_estado_id;

DROP TABLE dinero;
DROP TABLE bono;

CREATE TABLE bono (
  bono_id int NOT NULL,
  bono_codigo varchar(20) NOT NULL,
  bono_descripcion varchar(100) NOT NULL,
  bono_monto int(11) NOT NULL,
  bono_estado_id int(11) NOT NULL,
  bono_tipo enum('usuario','masivo') NOT NULL,
  bono_creacion datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE bono ADD PRIMARY KEY (bono_id);
ALTER TABLE bono MODIFY bono_id int NOT NULL AUTO_INCREMENT;
ALTER TABLE bono ADD CONSTRAINT fk_bono_estado_id FOREIGN KEY (bono_estado_id) REFERENCES usuario_estado(usuario_estado_id);


CREATE TABLE dinero (
  dinero_id bigint(20) NOT NULL,
  dinero_remitente_id int(11) NOT NULL,
  dinero_monto int(11) NOT NULL,
  dinero_descripcion varchar(100) NOT NULL,
  dinero_bono varchar(30) NULL,
  dinero_creacion datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE dinero ADD PRIMARY KEY (dinero_id);
ALTER TABLE dinero MODIFY dinero_id bigint(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE dinero ADD CONSTRAINT fk_dinero_remitente_id FOREIGN KEY (dinero_remitente_id) REFERENCES remitente(remitente_id);

ALTER TABLE remitente ADD remitente_imagen CHAR(5) NULL AFTER remitente_regalo;
ALTER TABLE remitente ADD remitente_code INT(6) NULL AFTER remitente_password;

ALTER TABLE giro ADD giro_online VARCHAR(100) NULL AFTER giro_imagen;

ALTER TABLE remitente 
  ADD remitente_tipo_documento CHAR(1) NULL AFTER remitente_correo,
  ADD remitente_documento VARCHAR(20) NULL AFTER remitente_tipo_documento;
ALTER TABLE remitente ADD CONSTRAINT fk_remitente_tipo_documento FOREIGN KEY (remitente_tipo_documento) REFERENCES tipo_documento(tipo_documento_sigla);

CREATE TABLE epayco (
  epayco_remitente_id int NOT NULL,
  epayco_receptor_id int not null,
  epayco_valor_pesos bigint(20) not null,
  epayco_valor_bolivares bigint(20) not null,
  epayco_tasa float(5,4) not null,
  epayco_entidad varchar(20) not null,
  epayco_ref_payco varchar(50) not null,
  epayco_convenio varchar(50) not null,
  epayco_referencia varchar(100) not null,
  epayco_giro_id int null,
  epayco_creacion datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE epayco ADD CONSTRAINT uk_epayco_referencia UNIQUE (epayco_referencia);
ALTER TABLE epayco ADD CONSTRAINT fk_epayco_remitente_id FOREIGN KEY (epayco_remitente_id) REFERENCES remitente(remitente_id);
ALTER TABLE epayco ADD CONSTRAINT fk_epayco_receptor_id FOREIGN KEY (epayco_receptor_id) REFERENCES receptor(receptor_id);
ALTER TABLE epayco ADD CONSTRAINT fk_epayco_giro_id FOREIGN KEY (epayco_giro_id) REFERENCES giro(giro_id);

CREATE TABLE notificaciones (
  noti_id int NOT NULL,
  noti_titulo varchar(50) not null,
  noti_mensaje varchar(150) not null,
  noti_estado_id int not null,
  noti_creacion datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE notificaciones ADD PRIMARY KEY (noti_id);
ALTER TABLE notificaciones MODIFY noti_id int NOT NULL AUTO_INCREMENT;
ALTER TABLE notificaciones ADD CONSTRAINT fk_noti_estado_id FOREIGN KEY (noti_estado_id) REFERENCES usuario_estado(usuario_estado_id);

ALTER TABLE video ADD video_mensaje VARCHAR(500) NOT NULL AFTER video_titulo;
ALTER TABLE video ADD video_app ENUM('web','yampy_question','yampy_home') NOT NULL DEFAULT 'web' AFTER video_estado;

ALTER TABLE video CHANGE video_titulo video_titulo VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE video CHANGE video_url video_url VARCHAR(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE video CHANGE video_mensaje video_mensaje VARCHAR(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;

ALTER TABLE remitente ADD remitente_imagen_documento CHAR(5) NULL AFTER remitente_imagen;
ALTER TABLE usuario ADD usuario_codigo CHAR(10) NULL AFTER usuario_condiciones;
ALTER TABLE remitente ADD remitente_asesor INT NULL AFTER remitente_imagen_documento;
ALTER TABLE remitente ADD CONSTRAINT fk_remitente_asesor FOREIGN KEY (remitente_asesor) REFERENCES usuario(usuario_id);

ALTER TABLE banco ADD banco_sugerencia FLOAT(7,6) NOT NULL AFTER banco_tasa, ADD banco_tasa_yampy FLOAT(7,6) NOT NULL AFTER banco_sugerencia;

DROP TABLE tasa;

ALTER TABLE giro CHANGE giro_tasa_pdv giro_tasa_pdv DECIMAL(8,6) NOT NULL;

ALTER TABLE video ADD video_image VARCHAR(4) NULL AFTER video_app;



CREATE TABLE IF NOT EXISTS sura_ciudades(
  ciudad_id INT NOT NULL AUTO_INCREMENT,
  ciudad_nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ciudad_id),
  UNIQUE (ciudad_nombre)
);

INSERT INTO sura_ciudades (ciudad_nombre) VALUES 
("ABEJORRAL (ANTIOQUIA)"), ("ABREGO (NORTE DE SANTANDER)"), ("ABRIAQUÍ (ANTIOQUIA)"), ("ACACIAS (META)"), ("ACANDI (CHOCO)"), ("ACEVEDO (HUILA)"), ("ACHI (BOLIVAR)"), ("AGRADO (HUILA)"), ("AGUA DE DIOS (CUNDINAMARCA)"), ("AGUACHICA (CESAR)"), ("AGUADA (SANTANDER)"), ("AGUADAS (CALDAS)"), ("AGUAZUL (CASANARE)"), ("AGUSTIN CODAZZI (CESAR)"), ("AIPE (HUILA)"), ("ALBAN (CUNDINAMARCA)"), ("ALBAN (NARIÑO)"), ("ALBANIA (CAQUETA)"), ("ALBANIA (GUAJIRA)"), ("ALBANIA (SANTANDER)"), ("ALCALA (VALLE DEL CAUCA)"), ("ALDANA (NARIÑO)"), ("ALEJANDRIA (ANTIOQUIA)"), ("ALGARROBO (MAGDALENA)"), ("ALGECIRAS (HUILA)"), ("ALMAGUER (CAUCA)"), ("ALMEIDA (BOYACA)"), ("ALPUJARRA (TOLIMA)"), ("ALTAMIRA (HUILA)"), ("ALTO BAUDO (CHOCO)"), ("ALTOS DEL ROSARIO (BOLIVAR)"), ("ALVARADO (TOLIMA)"), ("AMAGA (ANTIOQUIA)"), ("AMALFI (ANTIOQUIA)"), ("AMANAVEN (VICHADA)"), ("AMBALEMA (TOLIMA)"), ("ANAPOIMA (CUNDINAMARCA)"), ("ANCUYA (NARIÑO)"), ("ANDAGOYA (CHOCO)"), ("ANDALUCIA (VALLE DEL CAUCA)"), ("ANDES (ANTIOQUIA)"), ("ANGELOPOLIS (ANTIOQUIA)"), ("ANGOSTURA (ANTIOQUIA)"), ("ANOLAIMA (CUNDINAMARCA)"), ("ANORI (ANTIOQUIA)"), ("ANSERMA (CALDAS)"), ("ANSERMANUEVO (VALLE DEL CAUCA)"), ("ANZA (ANTIOQUIA)"), ("ANZOATEGUI (TOLIMA)"), ("APARTADO (ANTIOQUIA)"), ("APIA (RISARALDA)"), ("APULO (CUNDINAMARCA)"), ("AQUITANIA (BOYACA)"), ("ARACATACA (MAGDALENA)"), ("ARANZAZU (CALDAS)"), ("ARARACUARA (AMAZONAS)"), ("ARATOCA (SANTANDER)"), ("ARAUCA (ARAUCA)"), ("ARAUQUITA (ARAUCA)"), ("ARBELAEZ (CUNDINAMARCA)"), ("ARBOLEDA (NARIÑO)"), ("ARBOLEDAS (NORTE DE SANTANDER)"), ("ARBOLETES (ANTIOQUIA)"), ("ARCABUCO (BOYACA)"), ("ARENAL (BOLIVAR)"), ("ARGELIA (ANTIOQUIA)"), ("ARGELIA (CAUCA)"), ("ARGELIA (VALLE DEL CAUCA)"), ("ARIGUANI (MAGDALENA)"), ("ARJONA (BOLIVAR)"), ("ARMENIA (ANTIOQUIA)"), ("ARMENIA (QUINDIO)"), ("ARMERO (TOLIMA)"), ("ARROYOHONDO (BOLIVAR)"), ("ASTREA (CESAR)"), ("ATACO (TOLIMA)"), ("AYAPEL (CORDOBA)"), ("BAGADO (CHOCO)"), ("BAHIA SOLANO (CHOCO)"), ("BAJO BAUDO (CHOCO)"), ("BALBOA (CAUCA)"), ("BALBOA (RISARALDA)"), ("BALCON DEL CESAR (CESAR)"), ("BARANOA (ATLANTICO)"), ("BARAYA (HUILA)"), ("BARBACOAS (NARIÑO)"), ("BARBOSA (ANTIOQUIA)"), ("BARBOSA (SANTANDER)"), ("BARICHARA (SANTANDER)"), ("BARRANCA DE UPIA (META)"), ("BARRANCABERMEJA (SANTANDER)"), ("BARRANCAS (GUAJIRA)"), ("BARRANCO DE LOBA (BOLIVAR)"), ("BARRANCO MINAS (GUAINIA)"), ("BARRANQUILLA (ATLANTICO)"), ("BECERRIL (CESAR)"), ("BELALCAZAR (CALDAS)"), ("BELEN (BOYACA)"), ("BELEN (NARIÑO)"), ("BELEN ANDAQUIES (CAQUETA)"), ("BELEN DE BAJIRA (CHOCO)"), ("BELEN DE LOS ANDAQUIES (CAQUETA)"), ("BELEN DE UMBRIA (RISARALDA)"), ("BELLAVISTA (CHOCO)"), ("BELLO (ANTIOQUIA)"), ("BELMIRA (ANTIOQUIA)"), ("BELTRAN (CUNDINAMARCA)"), ("BERBEO (BOYACA)"), ("BETANIA (ANTIOQUIA)"), ("BETE (CHOCO)"), ("BETEITIVA (BOYACA)"), ("BETULIA (ANTIOQUIA)"), ("BETULIA (SANTANDER)"), ("BETULIA (SUCRE)"), ("BITUIMA (CUNDINAMARCA)"), ("BOAVITA (BOYACA)"), ("BOCA DE PEPE (CHOCO)"), ("BOCAS DE SATINGA (NARIÑO)"), ("BOCHALEMA (NORTE DE SANTANDER)"), ("BOGOTA D.C. (BOGOTA D.C.)"), ("BOJACA (CUNDINAMARCA)"), ("BOJAYA (CHOCO)"), ("BOLIVAR (CAUCA)"), ("BOLIVAR (SANTANDER)"), ("BOLIVAR (VALLE DEL CAUCA)"), ("BOSA (BOGOTA D.C.)"), ("BOSCONIA (CESAR)"), ("BOYACA (BOYACA)"), ("BRICEÑO (ANTIOQUIA)"), ("BRICEÑO (BOYACA)"), ("BUCARAMANGA (SANTANDER)"), ("BUCARASICA (NORTE DE SANTANDER)"), ("BUENAVENTURA (VALLE DEL CAUCA)"), ("BUENAVISTA (BOYACA)"), ("BUENAVISTA (CORDOBA)"), ("BUENAVISTA (QUINDIO)"), ("BUENAVISTA (SUCRE)"), ("BUENOS AIRES (CAUCA)"), ("BUESACO (NARIÑO)"), ("BUGALAGRANDE (VALLE DEL CAUCA)"), ("BURITICA (ANTIOQUIA)"), ("BUSBANZA (BOYACA)"), ("CABRERA (CUNDINAMARCA)"), ("CABRERA (SANTANDER)"), ("CABUYARO (META)"), ("CACAHUAL (GUAINIA)"), ("CACERES (ANTIOQUIA)"), ("CACHIPAY (CUNDINAMARCA)"), ("CACHIRA (NORTE DE SANTANDER)"), ("CACOTA (NORTE DE SANTANDER)"), ("CAICEDO (ANTIOQUIA)"), ("CAICEDONIA (VALLE DEL CAUCA)"), ("CAIMITO (SUCRE)"), ("CAJAMARCA (TOLIMA)"), ("CAJIBIO (CAUCA)"), ("CAJICA (CUNDINAMARCA)"), ("CALAMAR (BOLIVAR)"), ("CALAMAR (GUAVIARE)"), ("CALARCA (QUINDIO)"), ("CALDAS (ANTIOQUIA)"), ("CALDAS (BOYACA)"), ("CALDONO (CAUCA)"), ("CALI (VALLE DEL CAUCA)"), ("CALIFORNIA (SANTANDER)"), ("CALIMA (VALLE DEL CAUCA)"), ("CALOTO (CAUCA)"), ("CAMPAMENTO (ANTIOQUIA)"), ("CAMPO ALEGRE (GUAINIA)"), ("CAMPO DE LA CRUZ (ATLANTICO)"), ("CAMPOALEGRE (HUILA)"), ("CAMPOHERMOSO (BOYACA)"), ("CANALETE (CORDOBA)"), ("CANDELARIA (ATLANTICO)"), ("CANDELARIA (VALLE DEL CAUCA)"), ("CANTAGALLO (BOLIVAR)"), ("CAÑASGORDAS (ANTIOQUIA)"), ("CAPARRAPI (CUNDINAMARCA)"), ("CAPITANEJO (SANTANDER)"), ("CAQUEZA (CUNDINAMARCA)"), ("CARACOLI (ANTIOQUIA)"), ("CARAMANTA (ANTIOQUIA)"), ("CARCASI (SANTANDER)"), ("CAREPA (ANTIOQUIA)"), ("CARMEN DE APICALA (TOLIMA)"), ("CARMEN DE CARUPA (CUNDINAMARCA)"), ("CAROLINA (ANTIOQUIA)"), ("CARTAGENA (BOLIVAR)"), ("CARTAGENA DEL CHAIRA (CAQUETA)"), ("CARTAGO (VALLE DEL CAUCA)"), ("CARURU (VAUPES)"), ("CASABE (ANTIOQUIA)"), ("CASABIANCA (TOLIMA)"), ("CASTILLA LA NUEVA (META)"), ("CASUARITO (VICHADA)"), ("CAUCASIA (ANTIOQUIA)"), ("CEPITA (SANTANDER)"), ("CERETE (CORDOBA)"), ("CERINZA (BOYACA)"), ("CERRITO (SANTANDER)"), ("CERRO SAN ANTONIO (MAGDALENA)"), ("CERTEGUI (CHOCO)"), ("CHACHAGUI (NARIÑO)"), ("CHAGUANI (CUNDINAMARCA)"), ("CHALAN (SUCRE)"), ("CHAMEZA (CASANARE)"), ("CHAPARRAL (TOLIMA)"), ("CHARALA (SANTANDER)"), ("CHARTA (SANTANDER)"), ("CHIA (CUNDINAMARCA)"), ("CHIBOLO (MAGDALENA)"), ("CHIGORODO (ANTIOQUIA)"), ("CHIMA (CORDOBA)"), ("CHIMA (SANTANDER)"), ("CHIMICHAGUA (CESAR)"), ("CHINACOTA (NORTE DE SANTANDER)"), ("CHINAVITA (BOYACA)"), ("CHINCHINA (CALDAS)"), ("CHINU (CORDOBA)"), ("CHIPAQUE (CUNDINAMARCA)"), ("CHIPATA (SANTANDER)"), ("CHIQUINQUIRA (BOYACA)"), ("CHIQUIZA (BOYACA)"), ("CHIRIGUANA (CESAR)"), ("CHISCAS (BOYACA)"), ("CHITA (BOYACA)"), ("CHITAGA (NORTE DE SANTANDER)"), ("CHITARAQUE (BOYACA)"), ("CHIVATA (BOYACA)"), ("CHIVOR (BOYACA)"), ("CHOACHI (CUNDINAMARCA)"), ("CHOCONTA (CUNDINAMARCA)"), ("CICUCO (BOLIVAR)"), ("CIENAGA (MAGDALENA)"), ("CIENAGA DE ORO (CORDOBA)"), ("CIENEGA (BOYACA)"), ("CIMITARRA (SANTANDER)"), ("CIRCASIA (QUINDIO)"), ("CISNEROS (ANTIOQUIA)"), ("CIUDAD BOLIVAR (ANTIOQUIA)"), ("CLEMENCIA (BOLIVAR)"), ("COCORNA (ANTIOQUIA)"), ("COELLO (TOLIMA)"), ("COGUA (CUNDINAMARCA)"), ("COLOMBIA (HUILA)"), ("COLON (NARIÑO)"), ("COLON (PUTUMAYO)"), ("COMBITA (BOYACA)"), ("CONCEPCION (ANTIOQUIA)"), ("CONCEPCION (SANTANDER)"), ("CONCORDIA (ANTIOQUIA)"), ("CONCORDIA (MAGDALENA)"), ("CONDOTO (CHOCO)"), ("CONFINES (SANTANDER)"), ("CONSACA (NARIÑO)"), ("CONTADERO (NARIÑO)"), ("CONTRATACIÓN (SANTANDER)"), ("CONVENCION (NORTE DE SANTANDER)"), ("COPACABANA (ANTIOQUIA)"), ("COPER (BOYACA)"), ("CORDOBA (BOLIVAR)"), ("CORDOBA (NARIÑO)"), ("CORDOBA (QUINDIO)"), ("CORINTO (CAUCA)"), ("COROMORO (SANTANDER)"), ("COROZAL (SUCRE)"), ("CORRALES (BOYACA)"), ("COTA (CUNDINAMARCA)"), ("COTORRA (CORDOBA)"), ("COVARACHIA (BOYACA)"), ("COVEÑAS (SUCRE)"), ("COYAIMA (TOLIMA)"), ("CRAVO NORTE (ARAUCA)"), ("CUASPUD (NARIÑO)"), ("CUBARA (BOYACA)"), ("CUBARRAL (META)"), ("CUCAITA (BOYACA)"), ("CUCUNUBA (CUNDINAMARCA)"), ("CUCUTA (NORTE DE SANTANDER)"), ("CUCUTILLA (NORTE DE SANTANDER)"), ("CUITIVA (BOYACA)"), ("CUMARAL (META)"), ("CUMARIBO (VICHADA)"), ("CUMBAL (NARIÑO)"), ("CUMBITARA (NARIÑO)"), ("CUNDAY (TOLIMA)"), ("CURBARADO (CHOCO)"), ("CURILLO (CAQUETA)"), ("CURITI (SANTANDER)"), ("CURUMANI (CESAR)"), ("DABEIBA (ANTIOQUIA)"), ("DAGUA (VALLE DEL CAUCA)"), ("DARIEN (VALLE DEL CAUCA)"), ("DESCONOCIDO/SIN MUNICIPIO (VICHADA)"), ("DIBULLA (GUAJIRA)"), ("DISTRACCION (GUAJIRA)"), ("DOLORES (TOLIMA)"), ("DON MATIAS (ANTIOQUIA)"), ("DOSQUEBRADAS (RISARALDA)"), ("DUITAMA (BOYACA)"), ("DURANIA (NORTE DE SANTANDER)"), ("EBEJICO (ANTIOQUIA)"), ("EL AGUILA (VALLE DEL CAUCA)"), ("EL BAGRE (ANTIOQUIA)"), ("EL BANCO (MAGDALENA)"), ("EL BORDO (CAUCA)"), ("EL CAIRO (VALLE DEL CAUCA)"), ("EL CALVARIO (META)"), ("EL CANTON DEL SAN PABLO (CHOCO)"), ("EL CARMEN (NORTE DE SANTANDER)"), ("EL CARMEN DE ATRATO (CHOCO)"), ("EL CARMEN DE BOLIVAR (BOLIVAR)"), ("EL CARMEN DE CHUCURI (SANTANDER)"), ("EL CARMEN DE VIBORAL (ANTIOQUIA)"), ("EL CASTILLO (META)"), ("EL CERRITO (VALLE DEL CAUCA)"), ("EL CHARCO (NARIÑO)"), ("EL COCUY (BOYACA)"), ("EL COLEGIO (CUNDINAMARCA)"), ("EL COPEY (CESAR)"), ("EL DIFICIL (MAGDALENA)"), ("EL DONCELLO (CAQUETA)"), ("EL DORADO (META)"), ("EL DOVIO (VALLE DEL CAUCA)"), ("EL ENCANTO (AMAZONAS)"), ("EL ESPINO (BOYACA)"), ("EL GUACAMAYO (SANTANDER)"), ("EL GUAMO (BOLIVAR)"), ("EL LITORAL DEL SAN JUAN (CHOCO)"), ("EL MOLINO (GUAJIRA)"), ("EL PASO (CESAR)"), ("EL PAUJIL (CAQUETA)"), ("EL PEÑOL (NARIÑO)"), ("EL PEÑON (BOLIVAR)"), ("EL PEÑON (CUNDINAMARCA)"), ("EL PEÑON (SANTANDER)"), ("EL PIÑON (MAGDALENA)"), ("EL PLAYON (SANTANDER)"), ("EL RETEN (MAGDALENA)"), ("EL RETORNO (GUAVIARE)"), ("EL RETORNO (VAUPES)"), ("EL ROBLE (SUCRE)"), ("EL ROSAL (CUNDINAMARCA)"), ("EL ROSARIO (NARIÑO)"), ("EL SANTUARIO (ANTIOQUIA)"), ("EL TABLON DE GOMEZ (NARIÑO)"), ("EL TAMBO (CAUCA)"), ("EL TAMBO (NARIÑO)"), ("EL TARRA (NORTE DE SANTANDER)"), ("EL ZULIA (NORTE DE SANTANDER)"), ("ELIAS (HUILA)"), ("ENCINO (SANTANDER)"), ("ENCISO (SANTANDER)"), ("ENGATIVA (BOGOTA D.C.)"), ("ENTRERRIOS (ANTIOQUIA)"), ("ENVIGADO (ANTIOQUIA)"), ("ESPINAL (TOLIMA)"), ("FACATATIVA (CUNDINAMARCA)"), ("FALAN (TOLIMA)"), ("FILADELFIA (CALDAS)"), ("FILANDIA (QUINDIO)"), ("FIRAVITOBA (BOYACA)"), ("FLANDES (TOLIMA)"), ("FLORENCIA (CAQUETA)"), ("FLORENCIA (CAUCA)"), ("FLORESTA (BOYACA)"), ("FLORIAN (SANTANDER)"), ("FLORIDA (VALLE DEL CAUCA)"), ("FLORIDABLANCA (SANTANDER)"), ("FOMEQUE (CUNDINAMARCA)"), ("FONSECA (GUAJIRA)"), ("FONTIBON (BOGOTA D.C.)"), ("FORTUL (ARAUCA)"), ("FOSCA (CUNDINAMARCA)"), ("FRANCISCO PIZARRO (NARIÑO)"), ("FREDONIA (ANTIOQUIA)"), ("FRESNO (TOLIMA)"), ("FRONTINO (ANTIOQUIA)"), ("FUENTE DE ORO (META)"), ("FUNDACION (MAGDALENA)"), ("FUNES (NARIÑO)"), ("FUNZA (CUNDINAMARCA)"), ("FUQUENE (CUNDINAMARCA)"), ("FUSAGASUGA (CUNDINAMARCA)"), ("GACHALA (CUNDINAMARCA)"), ("GACHANCIPA (CUNDINAMARCA)"), ("GACHANTIVA (BOYACA)"), ("GACHETA (CUNDINAMARCA)"), ("GALAN (SANTANDER)"), ("GALAPA (ATLANTICO)"), ("GALERAS (SUCRE)"), ("GAMA (CUNDINAMARCA)"), ("GAMARRA (CESAR)"), ("GAMBITA (SANTANDER)"), ("GAMEZA (BOYACA)"), ("GARAGOA (BOYACA)"), ("GARZON (HUILA)"), ("GENOVA (NARIÑO)"), ("GENOVA (QUINDIO)"), ("GETUCHA (CAQUETA)"), ("GIGANTE (HUILA)"), ("GINEBRA (VALLE DEL CAUCA)"), ("GIRALDO (ANTIOQUIA)"), ("GIRARDOT (CUNDINAMARCA)"), ("GIRARDOTA (ANTIOQUIA)"), ("GIRON (SANTANDER)"), ("GOMEZ PLATA (ANTIOQUIA)"), ("GONZALEZ (CESAR)"), ("GRAMALOTE (NORTE DE SANTANDER)"), ("GRANADA (ANTIOQUIA)"), ("GRANADA (CUNDINAMARCA)"), ("GRANADA (MAGDALENA)"), ("GRANADA (META)"), ("GUACA (SANTANDER)"), ("GUACAMAYAS (BOYACA)"), ("GUACARI (VALLE DEL CAUCA)"), ("GUACHENE (CAUCA)"), ("GUACHETA (CUNDINAMARCA)"), ("GUACHUCAL (NARIÑO)"), ("GUADALAJARA DE BUGA (VALLE DEL CAUCA)"), ("GUADALUPE (ANTIOQUIA)"), ("GUADALUPE (HUILA)"), ("GUADALUPE (SANTANDER)"), ("GUADUAS (CUNDINAMARCA)"), ("GUAITARILLA (NARIÑO)"), ("GUALMATAN (NARIÑO)"), ("GUAMAL (MAGDALENA)"), ("GUAMAL (META)"), ("GUAMO (TOLIMA)"), ("GUAPI (CAUCA)"), ("GUAPOTA (SANTANDER)"), ("GUARANDA (SUCRE)"), ("GUARNE (ANTIOQUIA)"), ("GUASCA (CUNDINAMARCA)"), ("GUATAPE (ANTIOQUIA)"), ("GUATAQUI (CUNDINAMARCA)"), ("GUATAVITA (CUNDINAMARCA)"), ("GUATEQUE (BOYACA)"), ("GUATICA (RISARALDA)"), ("GUAVATA (SANTANDER)"), ("GUAVIARE (GUAINIA)"), ("GUAYABAL DE SIQUIMA (CUNDINAMARCA)"), ("GUAYABETAL (CUNDINAMARCA)"), ("GUAYATA (BOYACA)"), ("GUEPSA (SANTANDER)"), ("GUICAN (BOYACA)"), ("GUTIERREZ (CUNDINAMARCA)"), ("HACARI (NORTE DE SANTANDER)"), ("HATILLO DE LOBA (BOLIVAR)"), ("HATO (SANTANDER)"), ("HATO COROZAL (CASANARE)"), ("HATONUEVO (GUAJIRA)"), ("HELICONIA (ANTIOQUIA)"), ("HERRAN (NORTE DE SANTANDER)"), ("HERVEO (TOLIMA)"), ("HISPANIA (ANTIOQUIA)"), ("HOBO (HUILA)"), ("HONDA (TOLIMA)"), ("IBAGUE (TOLIMA)"), ("ICONONZO (TOLIMA)"), ("ILES (NARIÑO)"), ("IMUES (NARIÑO)"), ("INIRIDA (GUAINIA)"), ("INZA (CAUCA)"), ("IPIALES (NARIÑO)"), ("IQUIRA (HUILA)"), ("ISTMINA (CHOCO)"), ("ITAGUI (ANTIOQUIA)"), ("ITUANGO (ANTIOQUIA)"), ("IZA (BOYACA)"), ("JAMBALO (CAUCA)"), ("JAMUNDI (VALLE DEL CAUCA)"), ("JARDIN (ANTIOQUIA)"), ("JENESANO (BOYACA)"), ("JERICO (ANTIOQUIA)"), ("JERICO (BOYACA)"), ("JERUSALEN (CUNDINAMARCA)"), ("JESUS MARIA (SANTANDER)"), ("JORDAN SUBE (SANTANDER)"), ("JUAN DE ACOSTA (ATLANTICO)"), ("JUNIN (CUNDINAMARCA)"), ("JURADO (CHOCO)"), ("LA APARTADA Y LA FRONTERA (CORDOBA)"), ("LA ARGENTINA (HUILA)"), ("LA BELLEZA (SANTANDER)"), ("LA CALERA (CUNDINAMARCA)"), ("LA CAPILLA (BOYACA)"), ("LA CEJA (ANTIOQUIA)"), ("LA CELIA (RISARALDA)"), ("LA CHORRERA (AMAZONAS)"), ("LA CRUZ (NARIÑO)"), ("LA CUMBRE (VALLE DEL CAUCA)"), ("LA DORADA (CALDAS)"), ("LA DORADA (PUTUMAYO)"), ("LA ESPERANZA (NORTE DE SANTANDER)"), ("LA ESTRELLA (ANTIOQUIA)"), ("LA FLORIDA (NARIÑO)"), ("LA GLORIA (CESAR)"), ("LA GUADALUPE (GUAINIA)"), ("LA HORMIGA (PUTUMAYO)"), ("LA JAGUA DE IBIRICO (CESAR)"), ("LA JAGUA DEL PILAR (GUAJIRA)"), ("LA LLANADA (NARIÑO)"), ("LA MACARENA (META)"), ("LA MAGDALENA (ANTIOQUIA)"), ("LA MERCED (CALDAS)"), ("LA MESA (CUNDINAMARCA)"), ("LA MONTAÑITA (CAQUETA)"), ("LA PALMA (CUNDINAMARCA)"), ("LA PAZ (CESAR)"), ("LA PAZ (SANTANDER)"), ("LA PEDRERA (AMAZONAS)"), ("LA PEÑA (CUNDINAMARCA)"), ("LA PINTADA (ANTIOQUIA)"), ("LA PLATA (HUILA)"), ("LA PLAYA (NORTE DE SANTANDER)"), ("LA PRIMAVERA (VICHADA)"), ("LA SALINA (CASANARE)"), ("LA SIERRA (CAUCA)"), ("LA TEBAIDA (QUINDIO)"), ("LA TOLA (NARIÑO)"), ("LA UNION (ANTIOQUIA)"), ("LA UNION (NARIÑO)"), ("LA UNION (SUCRE)"), ("LA UNION (VALLE DEL CAUCA)"), ("LA UVITA (BOYACA)"), ("LA VEGA (CAUCA)"), ("LA VEGA (CUNDINAMARCA)"), ("LA VICTORIA (BOYACA)"), ("LA VICTORIA (VALLE DEL CAUCA)"), ("LA VIRGINIA (RISARALDA)"), ("LABATECA (NORTE DE SANTANDER)"), ("LABRANZAGRANDE (BOYACA)"), ("LANDAZURI (SANTANDER)"), ("LEBRIJA (SANTANDER)"), ("LEIVA (NARIÑO)"), ("LEJANIAS (META)"), ("LENGUAZAQUE (CUNDINAMARCA)"), ("LERIDA (TOLIMA)"), ("LETICIA (AMAZONAS)"), ("LIBANO (TOLIMA)"), ("LIBORINA (ANTIOQUIA)"), ("LINARES (NARIÑO)"), ("LLORO (CHOCO)"), ("LOPEZ (CAUCA)"), ("LORICA (CORDOBA)"), ("LOS ANDES (NARIÑO)"), ("LOS CORDOBAS (CORDOBA)"), ("LOS PALMITOS (SUCRE)"), ("LOS PATIOS (NORTE DE SANTANDER)"), ("LOS SANTOS (SANTANDER)"), ("LOURDES (NORTE DE SANTANDER)"), ("LURUACO (ATLANTICO)"), ("MACANAL (BOYACA)"), ("MACARAVITA (SANTANDER)"), ("MACEO (ANTIOQUIA)"), ("MACHETA (CUNDINAMARCA)"), ("MADRID (CUNDINAMARCA)"), ("MAGANGUE (BOLIVAR)"), ("MAGUI (NARIÑO)"), ("MAHATES (BOLIVAR)"), ("MAICAO (GUAJIRA)"), ("MAJAGUAL (SUCRE)"), ("MALAGA (SANTANDER)"), ("MALAMBO (ATLANTICO)"), ("MALLAMA (NARIÑO)"), ("MANAGRU (CHOCO)"), ("MANATI (ATLANTICO)"), ("MANAURE (CESAR)"), ("MANAURE (GUAJIRA)"), ("MANI (CASANARE)"), ("MANIZALES (CALDAS)"), ("MANTA (CUNDINAMARCA)"), ("MANZANARES (CALDAS)"), ("MAPIRIPAN (META)"), ("MAPIRIPANA (GUAINIA)"), ("MARGARITA (BOLIVAR)"), ("MARIA LA BAJA (BOLIVAR)"), ("MARINILLA (ANTIOQUIA)"), ("MARIPI (BOYACA)"), ("MARIQUITA (TOLIMA)"), ("MARMATO (CALDAS)"), ("MARQUETALIA (CALDAS)"), ("MARSELLA (RISARALDA)"), ("MARULANDA (CALDAS)"), ("MATANZA (SANTANDER)"), ("MATICURU (CAQUETA)"), ("MEDELLIN (ANTIOQUIA)"), ("MEDINA (CUNDINAMARCA)"), ("MEDIO BAUDO (CHOCO)"), ("MELGAR (TOLIMA)"), ("MERCADERES (CAUCA)"), ("MESETAS (META)"), ("MILAN (CAQUETA)"), ("MIRAFLORES (BOYACA)"), ("MIRAFLORES (GUAVIARE)"), ("MIRAFLORES (VAUPES)"), ("MIRANDA (CAUCA)"), ("MIRITI PARANA (AMAZONAS)"), ("MISTRATO (RISARALDA)"), ("MITU (VAUPES)"), ("MOCOA (PUTUMAYO)"), ("MOGOTES (SANTANDER)"), ("MOLAGAVITA (SANTANDER)"), ("MOMIL (CORDOBA)"), ("MOMPOS (BOLIVAR)"), ("MONGUA (BOYACA)"), ("MONGUI (BOYACA)"), ("MONIQUIRA (BOYACA)"), ("MONTEBELLO (ANTIOQUIA)"), ("MONTECRISTO (BOLIVAR)"), ("MONTELIBANO (CORDOBA)"), ("MONTENEGRO (QUINDIO)"), ("MONTERIA (CORDOBA)"), ("MONTERREY (CASANARE)"), ("MOÑITOS (CORDOBA)"), ("MORALES (BOLIVAR)"), ("MORALES (CAUCA)"), ("MORELIA (CAQUETA)"), ("MORICHAL (VAUPES)"), ("MORICHAL NUEVO (GUAINIA)"), ("MORROA (SUCRE)"), ("MOSQUERA (CUNDINAMARCA)"), ("MOSQUERA (NARIÑO)"), ("MOTAVITA (BOYACA)"), ("MURILLO (TOLIMA)"), ("MURINDO (ANTIOQUIA)"), ("MUTATA (ANTIOQUIA)"), ("MUTISCUA (NORTE DE SANTANDER)"), ("MUZO (BOYACA)"), ("NARIÑO (ANTIOQUIA)"), ("NARIÑO (CUNDINAMARCA)"), ("NARIÑO (NARIÑO)"), ("NATAGA (HUILA)"), ("NATAGAIMA (TOLIMA)"), ("NECHI (ANTIOQUIA)"), ("NECOCLI (ANTIOQUIA)"), ("NEIRA (CALDAS)"), ("NEIVA (HUILA)"), ("NEMOCON (CUNDINAMARCA)"), ("NILO (CUNDINAMARCA)"), ("NIMAIMA (CUNDINAMARCA)"), ("NOBSA (BOYACA)"), ("NOCAIMA (CUNDINAMARCA)"), ("NORCASIA (CALDAS)"), ("NOVITA (CHOCO)"), ("NUEVA ANTIOQUIA (VICHADA)"), ("NUEVO COLON (BOYACA)"), ("NUNCHIA (CASANARE)"), ("NUQUI (CHOCO)"), ("OBANDO (VALLE DEL CAUCA)"), ("OCAMONTE (SANTANDER)"), ("OCAÑA (NORTE DE SANTANDER)"), ("OIBA (SANTANDER)"), ("OICATA (BOYACA)"), ("OLAYA (ANTIOQUIA)"), ("OLAYA HERRERA (NARIÑO)"), ("ONZAGA (SANTANDER)"), ("OPORAPA (HUILA)"), ("ORITO (PUTUMAYO)"), ("OROCUE (CASANARE)"), ("ORTEGA (TOLIMA)"), ("OSPINA (NARIÑO)"), ("OTANCHE (BOYACA)"), ("OVEJAS (SUCRE)"), ("PACHAVITA (BOYACA)"), ("PACHO (CUNDINAMARCA)"), ("PACOA (AMAZONAS)"), ("PACOA (VAUPES)"), ("PACORA (CALDAS)"), ("PADILLA (CAUCA)"), ("PAEZ (BOYACA)"), ("PAEZ (CAUCA)"), ("PAICOL (HUILA)"), ("PAILITAS (CESAR)"), ("PAIMADO (CHOCO)"), ("PAIME (CUNDINAMARCA)"), ("PAIPA (BOYACA)"), ("PAJARITO (BOYACA)"), ("PALERMO (HUILA)"), ("PALESTINA (CALDAS)"), ("PALESTINA (HUILA)"), ("PALMAR (SANTANDER)"), ("PALMAR DE VARELA (ATLANTICO)"), ("PALMAS DEL SOCORRO (SANTANDER)"), ("PALMIRA (VALLE DEL CAUCA)"), ("PALMITO (SUCRE)"), ("PALOCABILDO (TOLIMA)"), ("PAMPLONA (NORTE DE SANTANDER)"), ("PAMPLONITA (NORTE DE SANTANDER)"), ("PANA PANA (GUAINIA)"), ("PANDI (CUNDINAMARCA)"), ("PANQUEBA (BOYACA)"), ("PAPUNAUA (VAUPES)"), ("PARAMO (SANTANDER)"), ("PARATEBUENO (CUNDINAMARCA)"), ("PASCA (CUNDINAMARCA)"), ("PASTO (NARIÑO)"), ("PATIA (CAUCA)"), ("PAUNA (BOYACA)"), ("PAYA (BOYACA)"), ("PAZ DE ARIPORO (CASANARE)"), ("PAZ DE RIO (BOYACA)"), ("PEDRAZA (MAGDALENA)"), ("PELAYA (CESAR)"), ("PENSILVANIA (CALDAS)"), ("PEÑOL (ANTIOQUIA)"), ("PEQUE (ANTIOQUIA)"), ("PEREIRA (RISARALDA)"), ("PESCA (BOYACA)"), ("PIAMONTE (CAUCA)"), ("PIEDECUESTA (SANTANDER)"), ("PIEDRAS (TOLIMA)"), ("PIENDAMO (CAUCA)"), ("PIJAO (QUINDIO)"), ("PIJIÑO (MAGDALENA)"), ("PINCHOTE (SANTANDER)"), ("PINILLOS (BOLIVAR)"), ("PIOJO (ATLANTICO)"), ("PISBA (BOYACA)"), ("PITAL (HUILA)"), ("PITALITO (HUILA)"), ("PIVIJAY (MAGDALENA)"), ("PLANADAS (TOLIMA)"), ("PLANETA RICA (CORDOBA)"), ("PLATO (MAGDALENA)"), ("POLICARPA (NARIÑO)"), ("POLONUEVO (ATLANTICO)"), ("PONEDERA (ATLANTICO)"), ("POPAYAN (CAUCA)"), ("PORE (CASANARE)"), ("POTOSI (NARIÑO)"), ("PRADERA (VALLE DEL CAUCA)"), ("PRADO - SEVILLA (MAGDALENA)"), ("PRADO (TOLIMA)"), ("PROVIDENCIA (NARIÑO)"), ("PROVIDENCIA (SAN ANDRES Y PROVIDENCIA)"), ("PUEBLO BELLO (CESAR)"), ("PUEBLO NUEVO (CORDOBA)"), ("PUEBLO RICO (RISARALDA)"), ("PUEBLORRICO (ANTIOQUIA)"), ("PUEBLOVIEJO (MAGDALENA)"), ("PUENTE NACIONAL (SANTANDER)"), ("PUERRES (NARIÑO)"), ("PUERTO ALEGRIA (AMAZONAS)"), ("PUERTO ARICA (AMAZONAS)"), ("PUERTO ASIS (PUTUMAYO)"), ("PUERTO BERRIO (ANTIOQUIA)"), ("PUERTO BOYACA (BOYACA)"), ("PUERTO CAICEDO (PUTUMAYO)"), ("PUERTO CARREÑO (VICHADA)"), ("PUERTO COLOMBIA (ATLANTICO)"), ("PUERTO COLOMBIA (GUAINIA)"), ("PUERTO CONCORDIA (META)"), ("PUERTO ESCONDIDO (CORDOBA)"), ("PUERTO GAITAN (META)"), ("PUERTO GUZMAN (PUTUMAYO)"), ("PUERTO LEGUIZAMO (PUTUMAYO)"), ("PUERTO LIBERTADOR (CORDOBA)"), ("PUERTO LLERAS (META)"), ("PUERTO LOPEZ (META)"), ("PUERTO MURILLO (VICHADA)"), ("PUERTO NARE (ANTIOQUIA)"), ("PUERTO NARIÑO (AMAZONAS)"), ("PUERTO NARIÑO (VICHADA)"), ("PUERTO PARRA (SANTANDER)"), ("PUERTO RICO (BOLIVAR)"), ("PUERTO RICO (CAQUETA)"), ("PUERTO RICO (META)"), ("PUERTO RONDON (ARAUCA)"), ("PUERTO SALGAR (CUNDINAMARCA)"), ("PUERTO SANTANDER (AMAZONAS)"), ("PUERTO SANTANDER (NORTE DE SANTANDER)"), ("PUERTO TEJADA (CAUCA)"), ("PUERTO TRIUNFO (ANTIOQUIA)"), ("PUERTO WILCHES (SANTANDER)"), ("PULI (CUNDINAMARCA)"), ("PUNTA DE PIEDRAS (MAGDALENA)"), ("PUPIALES (NARIÑO)"), ("PURACE (CAUCA)"), ("PURIFICACION (TOLIMA)"), ("PURISIMA (CORDOBA)"), ("QUEBRADANEGRA (CUNDINAMARCA)"), ("QUETAME (CUNDINAMARCA)"), ("QUIBDO (CHOCO)"), ("QUIMBAYA (QUINDIO)"), ("QUINCHIA (RISARALDA)"), ("QUIPAMA (BOYACA)"), ("QUIPILE (CUNDINAMARCA)"), ("RAGONVALIA (NORTE DE SANTANDER)"), ("RAMIRIQUI (BOYACA)"), ("RAQUIRA (BOYACA)"), ("RECETOR (CASANARE)"), ("REGIDOR (BOLIVAR)"), ("REMEDIOS (ANTIOQUIA)"), ("REMOLINO (MAGDALENA)"), ("REPELON (ATLANTICO)"), ("RESTREPO (META)"), ("RESTREPO (VALLE DEL CAUCA)"), ("RETIRO (ANTIOQUIA)"), ("RICAURTE (COLOSO)"), ("RICAURTE (CUNDINAMARCA)"), ("RICAURTE (NARIÑO)"), ("RIO DE ORO (CESAR)"), ("RIO QUITO (CHOCO)"), ("RIO VIEJO (BOLIVAR)"), ("RIOBLANCO (TOLIMA)"), ("RIOFRIO (VALLE DEL CAUCA)"), ("RIOHACHA (GUAJIRA)"), ("RIONEGRO (ANTIOQUIA)"), ("RIONEGRO (SANTANDER)"), ("RIOSUCIO (CALDAS)"), ("RIOSUCIO (CHOCO)"), ("RISARALDA (CALDAS)"), ("RIVERA (HUILA)"), ("ROBERTO PAYAN (NARIÑO)"), ("ROLDANILLO (VALLE DEL CAUCA)"), ("RONCESVALLES (TOLIMA)"), ("RONDON (BOYACA)"), ("ROSAS (CAUCA)"), ("ROVIRA (TOLIMA)"), ("SABANA DE TORRES (SANTANDER)"), ("SABANAGRANDE (ATLANTICO)"), ("SABANALARGA (ANTIOQUIA)"), ("SABANALARGA (ATLANTICO)"), ("SABANALARGA (CASANARE)"), ("SABANETA (ANTIOQUIA)"), ("SABOYA (BOYACA)"), ("SACAMA (CASANARE)"), ("SACHICA (BOYACA)"), ("SAHAGUN (CORDOBA)"), ("SALADOBLANCO (HUILA)"), ("SALAHONDA (NARIÑO)"), ("SALAMINA (CALDAS)"), ("SALAMINA (MAGDALENA)"), ("SALAZAR (NORTE DE SANTANDER)"), ("SALDAÑA (TOLIMA)"), ("SALENTO (QUINDIO)"), ("SALGAR (ANTIOQUIA)"), ("SAMACA (BOYACA)"), ("SAMANA (CALDAS)"), ("SAMANIEGO (NARIÑO)"), ("SAMPUES (SUCRE)"), ("SAN AGUSTIN (HUILA)"), ("SAN ALBERTO (CESAR)"), ("SAN ANDRES (SAN ANDRES Y PROVIDENCIA)"), ("SAN ANDRES (SANTANDER)"), ("SAN ANDRES DE CUERQUIA (ANTIOQUIA)"), ("SAN ANDRES SOTAVENTO (CORDOBA)"), ("SAN ANGEL (MAGDALENA)"), ("SAN ANTERO (CORDOBA)"), ("SAN ANTONIO (TOLIMA)"), ("SAN ANTONIO DEL TEQUENDAMA (CUNDINAMARCA)"), ("SAN BENITO (SANTANDER)"), ("SAN BENITO ABAD (SUCRE)"), ("SAN BERNARDO (CUNDINAMARCA)"), ("SAN BERNARDO (NARIÑO)"), ("SAN BERNARDO DEL VIENTO (CORDOBA)"), ("SAN CALIXTO (NORTE DE SANTANDER)"), ("SAN CARLOS (ANTIOQUIA)"), ("SAN CARLOS (CORDOBA)"), ("SAN CARLOS DE GUAROA (META)"), ("SAN CAYETANO (CUNDINAMARCA)"), ("SAN CAYETANO (NORTE DE SANTANDER)"), ("SAN CRISTOBAL (BOLIVAR)"), ("SAN DIEGO (CESAR)"), ("SAN EDUARDO (BOYACA)"), ("SAN ESTANISLAO DE KOSTKA (BOLIVAR)"), ("SAN FELIPE (GUAINIA)"), ("SAN FERNANDO (BOLIVAR)"), ("SAN FRANCISCO (ANTIOQUIA)"), ("SAN FRANCISCO (CUNDINAMARCA)"), ("SAN FRANCISCO (PUTUMAYO)"), ("SAN GIL (SANTANDER)"), ("SAN JACINTO (BOLIVAR)"), ("SAN JACINTO DEL CAUCA (BOLIVAR)"), ("SAN JERONIMO (ANTIOQUIA)"), ("SAN JOAQUIN (SANTANDER)"), ("SAN JOSE (CALDAS)"), ("SAN JOSE D OCUN (VICHADA)"), ("SAN JOSE DE ISNOS (HUILA)"), ("SAN JOSE DE LA MONTAÑA (ANTIOQUIA)"), ("SAN JOSE DE MIRANDA (SANTANDER)"), ("SAN JOSE DE PARE (BOYACA)"), ("SAN JOSE DEL FRAGUA (CAQUETA)"), ("SAN JOSE DEL GUAVIARE (GUAVIARE)"), ("SAN JOSE DEL PALMAR (CHOCO)"), ("SAN JUAN DE ARAMA (META)"), ("SAN JUAN DE RIO SECO (CUNDINAMARCA)"), ("SAN JUAN DE URABA (ANTIOQUIA)"), ("SAN JUAN DEL CESAR (GUAJIRA)"), ("SAN JUAN NEPOMUCENO (BOLIVAR)"), ("SAN JUANITO (META)"), ("SAN LORENZO (NARIÑO)"), ("SAN LUIS (ANTIOQUIA)"), ("SAN LUIS (TOLIMA)"), ("SAN LUIS DE GACENO (BOYACA)"), ("SAN LUIS DE PALENQUE (CASANARE)"), ("SAN MARCOS (SUCRE)"), ("SAN MARTIN (CESAR)"), ("SAN MARTIN (META)"), ("SAN MARTIN DE LOBA (BOLIVAR)"), ("SAN MATEO (BOYACA)"), ("SAN MIGUEL (PUTUMAYO)"), ("SAN MIGUEL (SANTANDER)"), ("SAN MIGUEL DE SEMA (BOYACA)"), ("SAN ONOFRE (SUCRE)"), ("SAN PABLO (BOLIVAR)"), ("SAN PABLO (NARIÑO)"), ("SAN PABLO DE BORBUR (BOYACA)"), ("SAN PEDRO (ANTIOQUIA)"), ("SAN PEDRO (SUCRE)"), ("SAN PEDRO (VALLE DEL CAUCA)"), ("SAN PEDRO DE CARTAGO (NARIÑO)"), ("SAN PEDRO DE URABA (ANTIOQUIA)"), ("SAN PELAYO (CORDOBA)"), ("SAN RAFAEL (ANTIOQUIA)"), ("SAN RAFAEL DEL DOS (CHOCO)"), ("SAN ROQUE (ANTIOQUIA)"), ("SAN SEBASTIAN (CAUCA)"), ("SAN SEBASTIAN DE BUENAVISTA (MAGDALENA)"), ("SAN VICENTE (ANTIOQUIA)"), ("SAN VICENTE C (CAQUETA)"), ("SAN VICENTE DE CHUCURI (SANTANDER)"), ("SAN VICENTE DEL CAGUAN (CAQUETA)"), ("SAN ZENON (MAGDALENA)"), ("SANDONA (NARIÑO)"), ("SANTA ANA (MAGDALENA)"), ("SANTA BARBARA (ANTIOQUIA)"), ("SANTA BARBARA (NARIÑO)"), ("SANTA BARBARA (SANTANDER)"), ("SANTA BARBARA DE PINTO (MAGDALENA)"), ("SANTA CATALINA (BOLIVAR)"), ("SANTA GENOVEVA DE DOCORDO (CHOCO)"), ("SANTA HELENA DEL OPON (SANTANDER)"), ("SANTA ISABEL (TOLIMA)"), ("SANTA LUCIA (ATLANTICO)"), ("SANTA MARIA (BOYACA)"), ("SANTA MARIA (HUILA)"), ("SANTA MARTA (MAGDALENA)"), ("SANTA RITA (CHOCO)"), ("SANTA ROSA (CAUCA)"), ("SANTA ROSA DE CABAL (RISARALDA)"), ("SANTA ROSA DE LIMA (BOLIVAR)"), ("SANTA ROSA DE OSOS (ANTIOQUIA)"), ("SANTA ROSA DE VITERBO (BOYACA)"), ("SANTA ROSA DEL SUR (BOLIVAR)"), ("SANTA ROSALIA (VICHADA)"), ("SANTA SOFIA (BOYACA)"), ("SANTACRUZ (NARIÑO)"), ("SANTAFE DE ANTIOQUIA (ANTIOQUIA)"), ("SANTANA (BOYACA)"), ("SANTANDER DE QUILICHAO (CAUCA)"), ("SANTIAGO (NORTE DE SANTANDER)"), ("SANTIAGO (PUTUMAYO)"), ("SANTO DOMINGO (ANTIOQUIA)"), ("SANTO TOMAS (ATLANTICO)"), ("SANTUARIO (RISARALDA)"), ("SAPUYES (NARIÑO)"), ("SARAVENA (ARAUCA)"), ("SARDINATA (NORTE DE SANTANDER)"), ("SASAIMA (CUNDINAMARCA)"), ("SATIVANORTE (BOYACA)"), ("SATIVASUR (BOYACA)"), ("SEGOVIA (ANTIOQUIA)"), ("SESQUILE (CUNDINAMARCA)"), ("SEVILLA (VALLE DEL CAUCA)"), ("SIACHOQUE (BOYACA)"), ("SIBATE (CUNDINAMARCA)"), ("SIBUNDOY (PUTUMAYO)"), ("SILOS (NORTE DE SANTANDER)"), ("SILVANIA (CUNDINAMARCA)"), ("SILVIA (CAUCA)"), ("SIMACOTA (SANTANDER)"), ("SIMIJACA (CUNDINAMARCA)"), ("SIMITI (BOLIVAR)"), ("SINCE (SUCRE)"), ("SINCELEJO (SUCRE)"), ("SIPI (CHOCO)"), ("SITIONUEVO (MAGDALENA)"), ("SOACHA (CUNDINAMARCA)"), ("SOATA (BOYACA)"), ("SOCHA (BOYACA)"), ("SOCORRO (SANTANDER)"), ("SOCOTA (BOYACA)"), ("SOGAMOSO (BOYACA)"), ("SOLANO (CAQUETA)"), ("SOLEDAD (ATLANTICO)"), ("SOLITA (CAQUETA)"), ("SOMONDOCO (BOYACA)"), ("SONSON (ANTIOQUIA)"), ("SOPETRAN (ANTIOQUIA)"), ("SOPLAVIENTO (BOLIVAR)"), ("SOPO (CUNDINAMARCA)"), ("SORA (BOYACA)"), ("SORACA (BOYACA)"), ("SOTAQUIRA (BOYACA)"), ("SOTARA (CAUCA)"), ("SUAITA (SANTANDER)"), ("SUAN (ATLANTICO)"), ("SUAREZ (CAUCA)"), ("SUAREZ (TOLIMA)"), ("SUAZA (HUILA)"), ("SUBA (BOGOTA D.C.)"), ("SUBACHOQUE (CUNDINAMARCA)"), ("SUCRE (CAUCA)"), ("SUCRE (SANTANDER)"), ("SUCRE (SUCRE)"), ("SUESCA (CUNDINAMARCA)"), ("SUPATA (CUNDINAMARCA)"), ("SUPIA (CALDAS)"), ("SURATA (SANTANDER)"), ("SUSA (CUNDINAMARCA)"), ("SUSACON (BOYACA)"), ("SUTAMARCHAN (BOYACA)"), ("SUTATAUSA (CUNDINAMARCA)"), ("SUTATENZA (BOYACA)"), ("TABIO (CUNDINAMARCA)"), ("TADO (CHOCO)"), ("TALAIGUA NUEVO (BOLIVAR)"), ("TAMALAMEQUE (CESAR)"), ("TAMARA (CASANARE)"), ("TAME (ARAUCA)"), ("TAMESIS (ANTIOQUIA)"), ("TAMINANGO (NARIÑO)"), ("TANGUA (NARIÑO)"), ("TARAIRA (VAUPES)"), ("TARAPACA (AMAZONAS)"), ("TARAZA (ANTIOQUIA)"), ("TARQUI (HUILA)"), ("TARSO (ANTIOQUIA)"), ("TASCO (BOYACA)"), ("TAURAMENA (CASANARE)"), ("TAUSA (CUNDINAMARCA)"), ("TELLO (HUILA)"), ("TENA (CUNDINAMARCA)"), ("TENERIFE (MAGDALENA)"), ("TENJO (CUNDINAMARCA)"), ("TENZA (BOYACA)"), ("TEORAMA (NORTE DE SANTANDER)"), ("TERUEL (HUILA)"), ("TESALIA (HUILA)"), ("TIBACUY (CUNDINAMARCA)"), ("TIBANA (BOYACA)"), ("TIBASOSA (BOYACA)"), ("TIBIRITA (CUNDINAMARCA)"), ("TIBU (NORTE DE SANTANDER)"), ("TIERRALTA (CORDOBA)"), ("TIMANA (HUILA)"), ("TIMBIO (CAUCA)"), ("TIMBIQUI (CAUCA)"), ("TINJACA (BOYACA)"), ("TIPACOQUE (BOYACA)"), ("TIQUISIO (BOLIVAR)"), ("TITIRIBI (ANTIOQUIA)"), ("TOCA (BOYACA)"), ("TOCAIMA (CUNDINAMARCA)"), ("TOCANCIPA (CUNDINAMARCA)"), ("TOGUI (BOYACA)"), ("TOLEDO (ANTIOQUIA)"), ("TOLEDO (NORTE DE SANTANDER)"), ("TOLU (SUCRE)"), ("TOLU VIEJO (SUCRE)"), ("TONA (SANTANDER)"), ("TOPAGA (BOYACA)"), ("TOPAIPI (CUNDINAMARCA)"), ("TORIBIO (CAUCA)"), ("TORO (VALLE DEL CAUCA)"), ("TOTA (BOYACA)"), ("TOTORO (CAUCA)"), ("TRINIDAD (CASANARE)"), ("TRUJILLO (VALLE DEL CAUCA)"), ("TUBARA (ATLANTICO)"), ("TULUA (VALLE DEL CAUCA)"), ("TUMACO (NARIÑO)"), ("TUNJA (BOYACA)"), ("TUNUNGUA (BOYACA)"), ("TUQUERRES (NARIÑO)"), ("TURBACO (BOLIVAR)"), ("TURBANA (BOLIVAR)"), ("TURBO (ANTIOQUIA)"), ("TURMEQUE (BOYACA)"), ("TUTA (BOYACA)"), ("TUTAZA (BOYACA)"), ("UBALA (CUNDINAMARCA)"), ("UBAQUE (CUNDINAMARCA)"), ("UBATE (CUNDINAMARCA)"), ("ULLOA (VALLE DEL CAUCA)"), ("UMBITA (BOYACA)"), ("UMPALA (SANTANDER)"), ("UNE (CUNDINAMARCA)"), ("UNGUIA (CHOCO)"), ("UNION PANAMERICANA (CHOCO)"), ("URAMITA (ANTIOQUIA)"), ("URIBE (META)"), ("URIBIA (GUAJIRA)"), ("URRAO (ANTIOQUIA)"), ("URUMITA (GUAJIRA)"), ("USAQUEN (BOGOTA D.C.)"), ("USIACURI (ATLANTICO)"), ("USME (BOGOTA D.C.)"), ("UTICA (CUNDINAMARCA)"), ("VALDIVIA (ANTIOQUIA)"), ("VALENCIA (CORDOBA)"), ("VALLE DE SAN JOSE (SANTANDER)"), ("VALLE DE SAN JUAN (TOLIMA)"), ("VALLE DEL GUAMUEZ (PUTUMAYO)"), ("VALLEDUPAR (CESAR)"), ("VALPARAISO (ANTIOQUIA)"), ("VALPARAISO (CAQUETA)"), ("VEGACHI (ANTIOQUIA)"), ("VELEZ (SANTANDER)"), ("VENADILLO (TOLIMA)"), ("VENECIA (ANTIOQUIA)"), ("VENECIA (CUNDINAMARCA)"), ("VENTAQUEMADA (BOYACA)"), ("VERGARA (CUNDINAMARCA)"), ("VERSALLES (VALLE DEL CAUCA)"), ("VETAS (SANTANDER)"), ("VIANI (CUNDINAMARCA)"), ("VICTORIA (CALDAS)"), ("VIGIA DEL FUERTE (ANTIOQUIA)"), ("VIJES (VALLE DEL CAUCA)"), ("VILLA AMAZONICA (PUTUMAYO)"), ("VILLA CARO (NORTE DE SANTANDER)"), ("VILLA DE LEYVA (BOYACA)"), ("VILLA DEL ROSARIO (NORTE DE SANTANDER)"), ("VILLA RICA (CAUCA)"), ("VILLAGARZON (PUTUMAYO)"), ("VILLAGOMEZ (CUNDINAMARCA)"), ("VILLAHERMOSA (TOLIMA)"), ("VILLAMARIA (CALDAS)"), ("VILLANUEVA (BOLIVAR)"), ("VILLANUEVA (CASANARE)"), ("VILLANUEVA (GUAJIRA)"), ("VILLANUEVA (SANTANDER)"), ("VILLAPINZON (CUNDINAMARCA)"), ("VILLARRICA (TOLIMA)"), ("VILLAVICENCIO (META)"), ("VILLAVIEJA (HUILA)"), ("VILLETA (CUNDINAMARCA)"), ("VIOTA (CUNDINAMARCA)"), ("VIRACACHA (BOYACA)"), ("VISTAHERMOSA (META)"), ("VITERBO (CALDAS)"), ("YACOPI (CUNDINAMARCA)"), ("YACUANQUER (NARIÑO)"), ("YAGUARA (HUILA)"), ("YALI (ANTIOQUIA)"), ("YARUMAL (ANTIOQUIA)"), ("YAVARATE (VAUPES)"), ("YOLOMBO (ANTIOQUIA)"), ("YONDO (ANTIOQUIA)"), ("YOPAL (CASANARE)"), ("YOTOCO (VALLE DEL CAUCA)"), ("YUMBO (VALLE DEL CAUCA)"), ("YUTO (CHOCO)"), ("ZAMBRANO (BOLIVAR)"), ("ZAPATOCA (SANTANDER)"), ("ZAPAYAN (MAGDALENA)"), ("ZARAGOZA (ANTIOQUIA)"), ("ZARZAL (VALLE DEL CAUCA)"), ("ZETAQUIRA (BOYACA)"), ("ZIPACON (CUNDINAMARCA)"), ("ZIPAQUIRA (CUNDINAMARCA)");

CREATE TABLE IF NOT EXISTS sura(
  sura_id INT NOT NULL AUTO_INCREMENT,
  sura_usuario_id INT NOT NULL,
  sura_metodo_pago VARCHAR(10) NOT NULL,
  sura_tipo_documento VARCHAR(10) NOT NULL,
  sura_documento VARCHAR(20) NOT NULL,
  sura_primer_nombre VARCHAR(20) NOT NULL,
  sura_segundo_nombre VARCHAR(20) NOT NULL,
  sura_primer_apellido VARCHAR(20) NOT NULL,
  sura_segundo_apellido VARCHAR(20) NOT NULL,
  sura_fecha_nacimiento DATE NOT NULL,
  sura_genero VARCHAR(10) NOT NULL,
  sura_correo VARCHAR(100) NOT NULL,
  sura_telefono VARCHAR(20) NOT NULL,
  sura_direccion VARCHAR(200) NOT NULL,
  sura_ciudad VARCHAR(100) NOT NULL,
  sura_poliza VARCHAR(50) NOT NULL,
  sura_recaudo BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (sura_id),
  CONSTRAINT fk_sura_usuario_id FOREIGN KEY (sura_usuario_id) REFERENCES usuario(usuario_id)
);

ALTER TABLE banco ADD banco_imagen VARCHAR(5) NULL AFTER banco_tasa;

ALTER TABLE usuario ADD usuario_pasarela VARCHAR(100) NULL AFTER usuario_codigo;

update usuario set usuario_pasarela = concat('2585-',usuario_telefono);

ALTER TABLE mensaje DROP FOREIGN KEY fk_mensaje_banco_id;
ALTER TABLE mensaje DROP mensaje_tipo, DROP mensaje_banco_id;



-- pendiente de pago -> pendiente de validacion (cuando se carga imagen)
-- pendiente de validacion -> pago validado, pago errado
-- pago errado -> pendiente de validacion
-- en proceso -> asignado, por corregir, corregido(cuando lo edita el mismo usuario), devuelto, exitoso
-- asignado -> por corregir, corregido(cuando lo edita el mismo usuario), devuelto, exitoso
-- por corregir -> corregido, devuelto
-- corregido -> exitoso, por corregir, devuelto
-- reclamo -> creclamo cerrado, devuelto (cuando se hace gito pero hay reclamo)
-- reclamo cerrado -> reclamo
-- rechazado -> devuelto (1 mes sin gestion)
-- exitoso -> reclamo
-- devuelto

algo anda mal con tu giro


-- administrador -> todo
-- cliente -> 
-- administrador de giradores -> 
-- girador -> 
-- validador de pagos
-- asesor